//! triton-kernels — a library of ready-to-use GPU kernels written in
//! the triton-rs DSL. Mirrors the high-quality patterns from Python
//! Triton (matmul tutorial, liger-kernel, unsloth, vLLM) so consumers
//! like `ferrum-infer-rs` can pull a kernel off the shelf instead of
//! authoring from scratch.
//!
//! # Layout
//!
//!   cache         kv_cache_append
//!   elementwise   vec_add, residual_add (+inplace), fused_silu_mul,
//!                 gelu, add_bias
//!   embedding     embedding_lookup
//!   norms         rms_norm, layer_norm, fused_add_rms_norm
//!   positional    rope_q / rope_k / rope_full (with positions table)
//!   projection    split_qkv, transpose_head_to_token
//!   reduction     softmax, cross_entropy_forward
//!
//! Each kernel exposes the same surface — a marker type with `module()`
//! / `mlir()` static fns:
//!
//! ```ignore
//! use triton_kernels::prelude::*;
//! let mlir_text = rms_norm_f32::<1024>::mlir();
//! ```

// `#![deny(missing_docs)]` would force every kernel struct generated by
// the `#[triton_kernel]` proc-macro to carry its own doc comment, but
// the macro doesn't (yet) lift the user's `///` doc comments onto the
// generated struct. Each *kernel function* is documented; that's what
// users actually read.

pub mod attention;
pub mod cache;
pub mod elementwise;
pub mod embedding;
pub mod norms;
pub mod positional;
pub mod projection;
pub mod reduction;

/// Re-exports of the most commonly-used kernels — the things most
/// projects will want once they `use triton_kernels::prelude::*`. Names
/// match their proc-macro-emitted struct names (snake_case rather than
/// the typical Rust PascalCase, with `#[allow(non_camel_case_types)]`).
pub mod prelude {
    pub use crate::cache::kv_cache_append_f32;
    pub use crate::elementwise::{
        add_bias_f32, fused_silu_mul_f32, fused_silu_mul_interleaved_f32, gelu_f32,
        residual_add_f32, residual_add_inplace_f32, vec_add_f32,
    };
    pub use crate::embedding::embedding_lookup_f32;
    pub use crate::norms::{fused_add_rms_norm_f32, layer_norm_f32, rms_norm_f32};
    pub use crate::positional::{rope_full_f32, rope_k_f32, rope_q_f32};
    pub use crate::projection::{
        qk_norm_rope_transpose_f32, rope_transpose_f32, split_qkv_f32,
        transpose_head_to_token_f32, transpose_token_to_head_f32,
    };
    pub use crate::reduction::{cross_entropy_forward_f32, softmax_f32};
    pub use crate::attention::{
        decode_attention_f32, decode_attention_hm_f32, batched_decode_attention_f32,
    };
}
