//! triton-kernels — a library of ready-to-use GPU kernels written in
//! the triton-rs DSL. Mirrors the high-quality patterns from Python
//! Triton (matmul tutorial, liger-kernel, unsloth, vLLM) so consumers
//! like `ferrum-infer-rs` can pull a kernel off the shelf instead of
//! authoring from scratch.
//!
//! # Layout
//!
//! Kernels are grouped by what they do, not by which source they came
//! from:
//!
//!   elementwise   vec_add, residual_add (+inplace), fused_silu_mul,
//!                 fused_geglu, gelu, add_bias
//!   norms         rms_norm, layer_norm, fused_add_rms_norm
//!   reduction     softmax, cross_entropy_forward
//!   positional    rope (Q-only / K-only — split for branch-free codegen)
//!   embedding     embedding_lookup
//!
//! Every kernel exposes the same surface — a marker type with a
//! `module()` static fn:
//!
//! ```ignore
//! use triton_kernels::norms::RmsNormF32;
//! let mlir_text = RmsNormF32::<1024>::mlir();
//! ```
//!
//! That MLIR text feeds `tools/mlir_to_cubin.py` (or, eventually, the
//! C ABI shim) to produce a launchable cubin.
//!
//! # Why not just use the kernels in `crates/triton-dsl/examples/`?
//!
//! Those are binaries (`cargo run --example ferrum_xxx`) for
//! dump/inspect workflows. This crate exposes them as library code so
//! downstream crates can `use triton_kernels::norms::RmsNormF32` and
//! call `module()` / `mlir()` from their own build scripts.

// `#![deny(missing_docs)]` would force every kernel struct generated by
// the `#[triton_kernel]` proc-macro to carry its own doc comment, but
// the macro doesn't (yet) lift the user's `///` doc comments onto the
// generated struct. Each *kernel function* is documented; that's what
// users actually read.

pub mod elementwise;
pub mod embedding;
pub mod norms;
pub mod positional;
pub mod reduction;

/// Re-exports of the most commonly-used kernels — the things most
/// projects will want once they `use triton_kernels::prelude::*`. Names
/// match their proc-macro-emitted struct names (snake_case rather than
/// the typical Rust PascalCase, with `#[allow(non_camel_case_types)]`).
pub mod prelude {
    pub use crate::elementwise::{
        add_bias_f32, fused_silu_mul_f32, gelu_f32, residual_add_f32, residual_add_inplace_f32,
        vec_add_f32,
    };
    pub use crate::embedding::embedding_lookup_f32;
    pub use crate::norms::{fused_add_rms_norm_f32, layer_norm_f32, rms_norm_f32};
    pub use crate::positional::{rope_k_f32, rope_q_f32};
    pub use crate::reduction::{cross_entropy_forward_f32, softmax_f32};
}
