//! MLIR text printer.
//!
//! Emits:
//!   - `module { ... }` for the top-level container
//!   - `tt.func public @name(%arg0: T0, ...) -> () { ... }` for each function
//!   - **Generic form** for body ops:
//!     `%r = "op.name"(%a, %b) {attr = val} : (Ta, Tb) -> Tr`
//!
//! Generic form is verbose but uniform — no per-op custom syntax to maintain.
//! Triton's MLIR parser accepts both forms; we trade printer prettiness for
//! Phase 2 simplicity. A custom-form pass can be added later.

use crate::module::{Func, Module};
use crate::op::{Op, Region};
use std::fmt::{self, Write};

const INDENT: &str = "  ";

impl fmt::Display for Module {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        writeln!(f, "module {{")?;
        for func in &self.funcs {
            print_func(f, func, 1)?;
        }
        writeln!(f, "}}")
    }
}

fn print_func(f: &mut fmt::Formatter<'_>, func: &Func, indent: usize) -> fmt::Result {
    write_indent(f, indent)?;
    // Match upstream Triton convention: `tt.func` takes no visibility keyword
    // in its custom parser. We grepped 481 lines of test/Triton/*.mlir and
    // found zero `tt.func public` — only `tt.func @name`. Print the keyword
    // only for the non-default Private visibility (which Triton may or may
    // not accept; not exercised by Phase 2).
    write!(f, "tt.func ")?;
    if func.visibility != crate::module::Visibility::Public {
        write!(f, "{} ", func.visibility.as_str())?;
    }
    write!(f, "@{}(", func.name)?;

    // Args: take SSA names from the entry block's args (canonical source).
    let entry_args = func
        .body
        .blocks
        .first()
        .map(|b| b.args.as_slice())
        .unwrap_or(&[]);

    for (i, arg) in entry_args.iter().enumerate() {
        if i > 0 {
            write!(f, ", ")?;
        }
        write!(f, "{}: {}", arg, arg.ty())?;
    }
    write!(f, ")")?;

    if !func.return_types.is_empty() {
        write!(f, " -> (")?;
        for (i, t) in func.return_types.iter().enumerate() {
            if i > 0 {
                write!(f, ", ")?;
            }
            write!(f, "{}", t)?;
        }
        write!(f, ")")?;
    }

    writeln!(f, " {{")?;
    print_region_body(f, &func.body, indent + 1)?;
    write_indent(f, indent)?;
    writeln!(f, "}}")
}

fn print_region(f: &mut fmt::Formatter<'_>, region: &Region, indent: usize) -> fmt::Result {
    writeln!(f, "({{")?;
    print_region_body(f, region, indent + 1)?;
    write_indent(f, indent)?;
    write!(f, "}})")
}

fn print_region_body(f: &mut fmt::Formatter<'_>, region: &Region, indent: usize) -> fmt::Result {
    // For now we only ever emit a single entry block per region. Multi-block
    // regions (with `^bb1:` labels and successors) are not generated by the
    // current builder.
    if let Some(block) = region.blocks.first() {
        for op in &block.ops {
            print_op(f, op, indent)?;
            writeln!(f)?;
        }
    }
    Ok(())
}

fn print_op(f: &mut fmt::Formatter<'_>, op: &Op, indent: usize) -> fmt::Result {
    write_indent(f, indent)?;

    // Result list: `%a, %b = `
    if !op.results.is_empty() {
        for (i, r) in op.results.iter().enumerate() {
            if i > 0 {
                write!(f, ", ")?;
            }
            write!(f, "{}", r)?;
        }
        write!(f, " = ")?;
    }

    // Op name (always quoted in generic form).
    write!(f, "\"{}\"(", op.name)?;
    for (i, o) in op.operands.iter().enumerate() {
        if i > 0 {
            write!(f, ", ")?;
        }
        write!(f, "{}", o)?;
    }
    write!(f, ")")?;

    // Optional regions.
    if !op.regions.is_empty() {
        write!(f, " ")?;
        for (i, r) in op.regions.iter().enumerate() {
            if i > 0 {
                write!(f, ", ")?;
            }
            print_region(f, r, indent)?;
        }
    }

    // Optional attributes dict.
    if !op.attrs.is_empty() {
        write!(f, " {{")?;
        for (i, (k, v)) in op.attrs.iter().enumerate() {
            if i > 0 {
                write!(f, ", ")?;
            }
            write!(f, "{} = {}", k, v)?;
        }
        write!(f, "}}")?;
    }

    // Function-type signature: `: (T1, T2) -> Tr` or `: (T1) -> (R1, R2)`.
    write!(f, " : (")?;
    for (i, o) in op.operands.iter().enumerate() {
        if i > 0 {
            write!(f, ", ")?;
        }
        write!(f, "{}", o.ty())?;
    }
    write!(f, ") -> ")?;
    match op.results.len() {
        0 => write!(f, "()")?,
        1 => write!(f, "{}", op.results[0].ty())?,
        _ => {
            write!(f, "(")?;
            for (i, r) in op.results.iter().enumerate() {
                if i > 0 {
                    write!(f, ", ")?;
                }
                write!(f, "{}", r.ty())?;
            }
            write!(f, ")")?;
        }
    }
    Ok(())
}

fn write_indent(f: &mut fmt::Formatter<'_>, level: usize) -> fmt::Result {
    for _ in 0..level {
        f.write_str(INDENT)?;
    }
    Ok(())
}

/// Pretty-print a [`Module`] as an owned `String`. Convenience wrapper.
pub fn print_module(m: &Module) -> String {
    let mut s = String::new();
    write!(&mut s, "{}", m).expect("formatting Module to String cannot fail");
    s
}
